import "./globals.css";
import Header from "./componenets/header";
import { poppins } from './font'

export const metadata = {
  title: "Home Helper",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased `}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
