import "@/app/globals.css";

import { poppins } from './font'
import Header from "./componenets/header";
import Footer from "./componenets/footer";

export const metadata = {
  title: "Home Helper",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased `}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
